### ISSUE TITLE
How to overwrite News-Template?

### ISSUE THREAD

**Issue by foobar13372** [bithost-gmbh/pdfviewhelpers#106]
I wanted to use the pre-shipped ext:news configuration, but overwrite the template. In my static site template (loaded after pdfviewhelpers) I put

```
[globalVar = TSFE:type = 28032013]
    plugin.tx_news {
        view {
            test = foo
            templateRootPaths {
                0 = EXT:my_ext/Resources/Private/Templates/Extension/PdfViewHelpers/News/
            }
        }
    }
[end]
```

The key `test` is arriving, but the `templateRootPaths` is not -- it's always the one from your template, even though the load order is correct. If I remove your template from the static includes, my template path is correctly set (but the whole other stuff from yours is mising then, obviously).

Is this a bug in your extension or in the TYPO3 core? Or am I missing something here?

**Comment by macjohnny** [comment]
@foobar13372 are you sure your template is included *after* the pdf view helpers static template?
https://github.com/bithost-gmbh/pdfviewhelpers/blob/0b253e6b833817e112181d250ecf919a4b7bd05b/Configuration/TypoScript/Extensions/News/setup.txt#L24-L31

**Comment by foobar13372** [comment]
Ah, forget it, the moment I submitted the issue, I realized that I wrote it in the wrong static file with a similar name... (which is loaded in a higher tree level). Now everythign works. Thanks anyways. :)
