### ISSUE TITLE
[Bug] Can't install extension over TER

### ISSUE THREAD

**Issue by medarob** [bithost-gmbh/pdfviewhelpers#113]
Hi,

I tried to download and install the extension in the TYPO3 backend (TER) but this didn't work.
I had to manually download the ZIP file and upload the extension.

Other extensions work, if I want to install those in the backend.

Can this be verified? Is this a bug?

**Comment by maechler** [comment]
Hi @medarob 

Thanks for reporting! I just tested installing the extension via TER on a fresh site and everything, including the examples, just worked fine.

What is the exact error you get? 
Does the error still occur if you remove the extension and try to reinstall?
Could it just have been a network error?

**Comment by medarob** [comment]
There is no error.
The orange status bar on top is loading, but after 20-30% it stops and the status bar is gone and no extension was installed. I tried another extension and that worked fine.

I deinstalled the extension, tried to download it again via the Extension Manager but the same error appears. I had to install it manually.

I tried to install the extension on my DEV system.

**Comment by macjohnny** [comment]
@medarob which typo3 version are you using?
could you set the php-loglevel to info and paste an excerpt from the php log?

**Comment by maechler** [comment]
@medarob Are there any errors in the server PHP error log or the TYPO3 protocol?

The extension `pdfviewhelpers` is about `23.3MB` in size, which is quite large compared to other extensions. That is because `TCPDF` is included in the extension itself in order to allow an easy installation over TER. Maybe that is what is causing the error.

**Comment by medarob** [comment]
Thank you for the help.

Our admin said there was no error in the server apache log... also the TYPO3 protocol does not show any sign of an error.

**Comment by maechler** [comment]
It would be nice if you could try to set the PHP log level to info and show an excerpt from the PHP log as @macjohnny suggested. If there is a problem with the size of the extension or something else, we would really like to add a note about this to the trouble shooting section in the documentation.

Can you reproduce this issue locally on your computer?

**Comment by medarob** [comment]
Ok, this is probably the info you are looking for? (I only changed the IP and the Domain.

[Fri Apr 12 08:57:28.291620 2019] [php7:error] [pid 12808] [client xx.xx.xx.xx:xxxxx] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 42338112 bytes) in /var/www/staging/typo3_src-8.7.24/typo3/sysext/extensionmanager/Classes/Utility/Connection/TerUtility.php on line 128, referer: http://[domain].de/typo3/index.php?M=tools_ExtensionmanagerExtensionmanager&moduleToken=0d8bdc0fbf396a71746eb5085b447f873c1525cc&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Baction%5D=ter&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Bcontroller%5D=List

A co-worker tried it aswell and the same error appeard.

**Comment by maechler** [comment]
Yes, it looks like the error we are looking for! =)
Can you try to increase the memory limit and try it again?

```
ini_set('memory_limit', '512M');
```

**Comment by medarob** [comment]
After changing the memory_limit the installation worked :)

**Comment by maechler** [comment]
@medarob Perfect, thanks! I will add a note about this to the trouble shooting section.

If you like the extension, please consider giving it a star :)

**Comment by medarob** [comment]
You mean here?
![grafik](https://user-images.githubusercontent.com/33951787/56026306-2439af00-5d14-11e9-822d-7351a2daba03.png)

**Comment by maechler** [comment]
I meant on GitHub (on the right when you scroll to the top of this page), but also a "heart" would be very appreciated! =)
