### ISSUE TITLE
HTML rendering of lists / only limited HTML support?

### ISSUE THREAD

**Issue by medarob** [bithost-gmbh/pdfviewhelpers#115]
Hi,

I just tested the html rendering but it does not work.
I have a `<ul>`-list and want that list to be devided into 2 equal parts (left and right). Therefor I wanted to use the CSS property "column-count" ( https://css-tricks.com/almanac/properties/c/column-count/ ). But this does not work. I get only one single list in the pdf.

```
<pdf:html>
 <style>
	.columns {
		-moz-column-count: 2;
		-moz-column-gap: 1em;
		-webkit-column-count: 2;
		-webkit-column-gap: 1em;
	        column-count: 2;
		column-gap: 1em;
	}
	ul {
		margin-top: 0;
	}
</style>
<div class="columns">
   <ul>
      <li>a</li>
      <li>b</li>
	<li>c</li>
	<li>d</li>
	<li>e</li>
	<li>f</li>
	<li>g</li>
	<li>h</li>
	<li>i</li>
	</ul>
</div>
</pdf:html>
```
Is the html-support somehow limited?

**Comment by macjohnny** [comment]
css support is very limited in TCPDF, see e.g. http://www.jennybeaumont.com/testing-tcpdf-css/
so this isn't something we could solve in `pdfviewhelpers`

**Comment by maechler** [comment]
If you are looking for and advanced HTML to PDF rendering, you might want to have a look at `mPDF`:

https://github.com/mpdf/mpdf
https://extensions.typo3.org/extension/mpdf/
