### ISSUE TITLE
Using SCSS as stylesheet

### ISSUE THREAD

**Issue by antonfries** [bithost-gmbh/pdfviewhelpers#125]
Hey,

is there a possibility to include already written scss-files into pdf-html-tags with the property "stylesheet" or similar?

We are generating a product datasheet and have already our custom fonts and scss classes for a fancy table and would output that on a pdf view. Is there maybe a more suitable extension for that?

Greetings, Anton

**Comment by macjohnny** [comment]
css support in tcpdf is very limited, see https://github.com/bithost-gmbh/pdfviewhelpers/issues/115#issuecomment-482517365

**Comment by maechler** [comment]
You could easily write your own ViewHelper that uses `scssphp` to compile your Sass files to CSS. Here is a quick and dirty example:

```PHP
CompileSassViewHelper extends AbstractViewHelper {
    public function render($sassFile) {
         $sassCompiler = new Leafo\ScssPhp\Compiler();

         return $sassCompiler->compile(file_get_contents($sassFile));
    }
}
```

```HTML
<pdf:html styleSheet="{yourext:compileSass(sassFile: 'EXT:/path/to/styles.scss')}">

</pdf:html>
```

But if you have a really complex layout than I would recommend having a look at `mPDF` as its `HTML` / `CSS` support is far better:
https://github.com/mpdf/mpdf
https://extensions.typo3.org/extension/mpdf/

Or else write a custom ViewHelper that uses the `TCPDF` API directly, but then you could not reuse your styles and markup.

**Comment by maechler** [comment]
@antonfries Did you come up with a solution for your problem?

**Comment by antonfries** [comment]
@maechler Ye, we came up with the decision to use the mpdf-Extension for TYPO3, because we don't need the diversity of pdf viewhelpers for our usage.

Thanks for your support!
