### ISSUE TITLE
Problems with Html ViewHelper

### ISSUE THREAD

**Issue by Behau** [bithost-gmbh/pdfviewhelpers#13]
I had a very big problem with your Html ViewHelper. When I tried to show some content from my database over a fluid command I got a blank side.

This is my code for the geneartion of the PDF-Document:

{namespace pdf=Bithost\Pdfviewhelpers\ViewHelpers}

```
<pdf:document outputDestination="I" title="Report">
    <pdf:page autoPageBreak="1">
        <pdf:html>
            <style>
                table {
                    color: #003300;
                    font-size: 8pt;
                    border: 1px solid black;
                }
                th {
                    font-weight: bold;
                    font-size: 8px;
                    text-align: left;
                    border-bottom: #eee 1px solid;
                    background-color: #eee;
                }
                td {
                    border: none;
                }
            </style>
            <f:for each="{uebersicht.fach}" as="fluid">
                <table class="first" cellpadding="2" cellspacing="5">
                    <tr>
                        <th>Fachübersicht</th>
                    </tr>
                    <tr>
                        <td>{uebersicht.fachid}&nbsp;{uebersicht.title}</td>
                    </tr>
                </table>
                <f:for each="{uebersicht.fach}" as="fach">
                    <table class="second" cellpadding="2" cellspacing="5">
                        <tr>
                            <th>Kurze Info</th>
                        </tr>
                        <tr>
                            <td>{fach.title}</td>
                        </tr>
                        <tr>
                            <th>Vielen dank an:</th>
                        </tr>
                        <tr>
                            <td>{fach.author}</td>
                        </tr>
                        <tr>
                            <th>Datum</th>
                        </tr>
                        <tr>
                            <td>{fach.date}</td>
                        </tr>
                        <tr>
                            <th>Eingaben:</th>
                        </tr>
                        <tr>
                            <th><f:format.htmlentitiesDecode value="{fach.content}" /></th>
                        </tr>
                    </table>
                </f:for>
            </f:for>
        </pdf:html>
    </pdf:page>
</pdf:document>

```

I found out, that the f.format.htmlentitiesDecode is never working. When I delete this code I get some times a text and sometimes no text. 
When I activate the header, then I see only the header and no html-content.

I hope you can help me. 
Best
Behau

**Comment by maechler** [comment]
Hi Behau

I just copied part of your template and that worked just fine, also with the ViewHelper `f.format.htmlentitiesDecode`.

**Code**
```html
{namespace pdf=Bithost\Pdfviewhelpers\ViewHelpers}

<pdf:document outputDestination="I" title="Report">
    <pdf:page autoPageBreak="1">
        <pdf:html>
            <style>
                table {
                    color: #003300;
                    font-size: 8pt;
                    border: 1px solid black;
                }
                th {
                    font-weight: bold;
                    font-size: 8px;
                    text-align: left;
                    border-bottom: #eee 1px solid;
                    background-color: #eee;
                }
                td {
                    border: none;
                }
            </style>

            <f:for each="{0: 'test', 1: 'M&uuml;ller &amp; Breuer'}" as="element">
                <table class="second" cellpadding="2" cellspacing="5">
                    <tr>
                        <td>{element}</td>
                    </tr>
                    <tr>
                        <th><f:format.htmlentitiesDecode value="{element}" /></th>
                    </tr>
                </table>
            </f:for>
        </pdf:html>
    </pdf:page>
</pdf:document>
```

**output**
<img width="642" alt="test_pdf" src="https://cloud.githubusercontent.com/assets/4113819/20864839/490bc242-b9ff-11e6-92dc-a81bde6b194e.png">

I think the problem you are describing could be because of a caching issue. When the frontend cache is empty the pdf gets first generated without any problems. However it will not be saved to the frontend cache but an empty entry will be. The second and third time you call the page with caching enabled, you get a blank page.
From pdfviewhelpers version 1.1.0 onward the frontend caching is disabled by default. 
What version are you using?
Try clearing the frontend cache and see if the pdf gets generated correctly.

If that is not the problem, please try to give more details on what exactly happens and when. Is there a message in the PHP error logs? What header are you referring to?

You could even send me your extension and I could try it out myself.

**Comment by Behau** [comment]
Hi maechler,

I found my problem.
Some parts of the content elements had <div> container in it and so the <f:format.htmlentitiesDecode value="{element}" /> part made some problems at the pdf-creation. 

This content comes from a form where people can entry information about courses etc. And someone had copied elements from a hompeage and with that, the <div> elements...

I will now write a code, that will cut off this <div> elements and save the light html code in the database.

Thank you for your help it seems that it is now working :)
