### ISSUE TITLE
Bmp & Jpeg Image Extensions

### ISSUE THREAD

**Issue by quak** [bithost-gmbh/pdfviewhelpers#135]
It seams that it isn't possible to use the image file extensions bmp & jpeg
I added the two image extensions to allowedImageTypes - i still get a error
![Screenshot 2019-10-29 at 12 21 58](https://user-images.githubusercontent.com/169361/67762904-c3bb5680-fa46-11e9-82a2-99d17b1b860d.png)

**Comment by macjohnny** [comment]
could you please give more details about your code?

**Comment by maechler** [comment]
@quak Using `JPEG` should definitely not be an issue, as you can see in your example here: https://docs.typo3.org/typo3cms/extensions/pdfviewhelpers/stable/Examples/BasicUsage/Index.html 

```html
<pdf:image src="EXT:pdfviewhelpers/Resources/Public/Examples/BasicUsage/Bithost.jpg" />
```

I suspect that you have an error in your path, could you please share your template?

**Comment by mediaessenz** [comment]
adding Type "jpeg"(with the e) in the default settings would be nice, btw.

**Comment by maechler** [comment]
@mediaessenz True, I just added it: https://github.com/bithost-gmbh/pdfviewhelpers/commit/4a709c301a45b48e4f1d61f87ad0ff477992d09c

**Comment by maechler** [comment]
@quak Could you solve the issue?

**Comment by quak** [comment]
@maechler thanks for your advice - i solved it for jpeg but not for bmp
I also added the both image types in the default settings but it just wont work for bmp
Guess i will just exclude bmp from the upload setting of my extension.

**Comment by maechler** [comment]
@quak Thanks for your reply! Under the hood `pdfviewhelpers` uses `TCPDF`, which in turn should support all image formats that are supported with GD or ImageMagick:

```
supports JPEG, PNG and SVG images natively, all images supported by 
GD (GD, GD2, GD2PART, GIF, JPEG, PNG, BMP, XBM, XPM) 
and all images supported via ImageMagick 
(http: www.imagemagick.org/www/formats.html)
-- https://tcpdf.org/
```

If `bmp` is not working, I guess there is a problem with your graphics library installed on the server.

If you like the extension, please consider giving it a star on GitHub =)

**Comment by quak** [comment]
yeah i know - if i will have some spare time i will investigate what went wrong and will post it here :)
