### ISSUE TITLE
Custom fonts not working inside of AvoidPageBreakViewHelper

### ISSUE THREAD

**Issue by MK-42** [bithost-gmbh/pdfviewhelpers#141]
Cloning the BasePDF instance in AvoidPageBreakViewHelper drops all custom fonts paths, so no custom fonts can be used in that context.

**Comment by maechler** [comment]
@MK-42 Thanks again for that high class pull request! I just released a new version `v2.2.2`, which contains your fix and uploaded it to TER.

If you like the project, please consider giving it a star on GitHub =)
