### ISSUE TITLE
Could not find Font definition file

### ISSUE THREAD

**Issue by SirZockholm** [bithost-gmbh/pdfviewhelpers#146]
As soon as I try to set a Font on a pdf:text field via parameter I recieve this error when generating the PDF in frontend.
I even tried to open the roboto-font from the example with the same outcome.
My guess is that it's not creating the .php file (or at least not in the right folder)

Or did I do something wrong?

In EXT:referenzen/Configuration/TypoScript**setup.typoscript**
`plugin.tx_pdfviewhelpers.settings.config.fonts {
    addTTFFont {
        roboto {
            path = EXT:pdfviewhelpers/Resources/Public/Examples/FullFeatureShowCase/Roboto.ttf
        }
    }
}`

In EXT:referenzen/Resources/Private/Templates/Referenz/**Pdf.html**
`<pdf:text padding="{bottom: 2}" fontFamily="roboto">{referenz.projectType}</pdf:text>`

**Comment by maechler** [comment]
@SirZockholm Could you please show the exact error message (including the file and line of code)? Which version of `pdfviewhelpers` are you using?

For `v2.2.0` and higher the font files should be written to `typo3temp/pdfviewhelpers/fonts/`, could you please check whether this folder exists and is writable / readable? Are the font files even generated?

For lower versions the font files would be written to `EXT:pdfviewhelpers/Resources/Private/PHP/tcpdf/fonts/`, which could be a problem if this folder is not writable by your web server user. If so, please try updating to the latest version.

**Comment by SirZockholm** [comment]
Hi @maechler 

Basically the title is the error-message `TCPDF ERROR: Could not include font definition file: roboto` when wanting to generate the PDF. Doesn't say on wich line or file.

Your latest entry in the changelog states v2.2.2.

The folder `typo3temp/pdfviewhelpers/fonts/` exist but no files are generated. It seems to be writable since I'm able to create files and folders in there via terminal. But I'm not sure if I checked correctly, can you tell me how to check for sure?

**Comment by maechler** [comment]
You should check the folder permissions using `ls -al typo3temp/pdfviewhelpers/fonts`. Additionally you should check with what user you tested the file creating using the command `whoami`. It is likely that the webserver user is different from the user you are using via terminal.

**Comment by SirZockholm** [comment]
Hi @maechler 
The folder permissions are `drwxr-xr-x`, user who created the file is the same as I use in terminal.
The site is currently on my development environment hosted locally.
I changed the folder permissions to 777 for testing but nothing changed.

**Comment by maechler** [comment]
Did you change the permissions only for the `fonts` folder or for the entire folder hierarchy? I think you would have to change the permissions recursively `chmod -R 777 typo3temp` to see whether it is a permissions issue.
Do you have the possibility to test this with a fresh TYPO3 installation with nothing installed except `EXT:pdfviewhelpers`?

Else It would be helpful if you could start debugging here: 
https://github.com/bithost-gmbh/pdfviewhelpers/blob/7cac90ce28a493da269731306192b33a01d6d44f/Classes/ViewHelpers/DocumentViewHelper.php#L191-L220

You could try to add the following after `$fontName = \TCPDF_FONTS::addTTFfont($path, $type, '', 32, $outputPath);`

```php
echo 'fontName: ' . $fontName . PHP_EOL;
echo 'outputPath: ' . $outputPath . PHP_EOL;
exit;
```

If this shows what you expect, then we would probably have to continue debugging within the method `\TCPDF_FONTS::addTTFfont`.

**Comment by SirZockholm** [comment]
Hi @maechler 
We had no luck with opening a fresh typo3 installation. Same problem at same point.

The echos you've sent me won't display. I also noticed your if at the beginning of the function:
`if (empty($this->settings['config']['fonts']['addTTFFont'])) { return; } `
Which is always true. Although I fill this array in
`EXT:referenzen/Configuration/TypoScript/setup.typoscript`

**Comment by maechler** [comment]
Can you verify that your `setup.typoscript` is really included using the `Template` module and the `TypoScript Object Browser`?
Does everything work if you do not add a custom font?
Where are you using the ViewHelpers, in a template of an Extbase Controller action?

**Comment by SirZockholm** [comment]
Yes this `setup.typoscript` is included and works. Other plugin settings have been set there as well. 
If there is no font defined everything works fine. But as soon as i put `fontFamily="anyFont"` in the template `/Templates/Referenz/Pdf.html` TCPDF throws an error.

**Comment by SirZockholm** [comment]
I noticed my mistake. I overwrote the typoscript again in our main plugin where it pointed to a wrong path. I slapped it in there at the beginning of this project and forgot about it.

Thanks for your time and hints to solve this Problem.

**Comment by maechler** [comment]
So now the custom fonts do work?

**Comment by SirZockholm** [comment]
The example fonts are displayed without a problem. Though the fonts we're trying to use are not displayed correctly. It's just hieroglyphs.
I recieved the font-files in .ttf format and even checked with an online Font-Converter tool. They are .ttf.
Now I don't get any errors whatsoever.

**Comment by maechler** [comment]
I see, thanks for your feedback! You could try setting the font type explicitly to `TrueTypeUnicode` or `TrueType`, see [CustomFonts](https://docs.typo3.org/typo3cms/extensions/pdfviewhelpers/stable/ConfigurationReference/CustomFonts/Index.html#typoscript).

Else you could probably try converting the font to a different format (https://tcpdf.org/docs/fonts/).

**Comment by SirZockholm** [comment]
I converted the Fonts [here](http://fonts.snm-portal.com/files/5e95a5081be81/result/metapro-black.php) and switched the Files generated from TCPDF. Now they are displayed correctly.
