### ISSUE TITLE
Add enc Parameter to addTTFFont

### ISSUE THREAD

**Issue by aadlung** [bithost-gmbh/pdfviewhelpers#156]
Depending on the fonts, using special characters (e.g. in Germany or Hungary) sometimes require to add a font with a utf-8 encoding (not on the document, but on the font), even if the file is of the type "TrueType".

The `DocumentViewHelper.php` file uses the following syntax:
```php
$fontName = \TCPDF_FONTS::addTTFfont($path, $type, '', 32, $outputPath);
```

So the encoding of the font file is always empty.

**Describe the solution you'd like**
I would ask to replace it with the following two lines, to enable adding "utf-8" as setting in typoscript:
```php
$enc = isset($ttfFont['enc']) ? $ttfFont['enc'] : '';
$fontName = \TCPDF_FONTS::addTTFfont($path, $type, '', 32, $outputPath);
```

**Comment by maechler** [comment]
@aadlung Thanks for creating this issue! We will sure add this as a parameter, I will also check whether it makes sense to add the remaining parameters.

**Comment by maechler** [comment]
I added this parameter in `v2.3.2` which I just released.
