### ISSUE TITLE
Backend usage

### ISSUE THREAD

**Issue by gvv1401** [bithost-gmbh/pdfviewhelpers#159]
Hi guys!
I'm trying to use the pdfviewhelpers in the backend module. I added the next line in my TypoScript-setup:
`module.tx_pdfviewhelpers < plugin.tx_pdfviewhelpers`
as described in #https://github.com/bithost-gmbh/pdfviewhelpers/pull/15
But I got an error: No pdfviewhelpers settings found. Please make sure you have included the static TypoScript template.
What is wrong? On FE all works fine.
PHP: v.7.2.27
TYPO3: v.10.4.3
pdfviewhelpers: v.2.3.1

**Comment by maechler** [comment]
@gvv1401 Could you check whether `module.tx_pdfviewhelpers` is being set using the TypoScript object browser?

<img width="817" alt="Screenshot 2020-06-01 at 21 56 40" src="https://user-images.githubusercontent.com/4113819/83448911-fa30d800-a452-11ea-9397-a9e79b87a17a.png">

Actually you do not even have to set it yourself, as it is being set in `setup.txt` of the static TypoScript template.

**Comment by gvv1401** [comment]
I found the reason! I have 3 pages tree in BE. On first tree pdfviewhelpers not included, on second and third - included. When I changed order of trees (first now last) all works.
![image](https://user-images.githubusercontent.com/10170885/83497180-c5f50000-a4c2-11ea-90f8-24672121ac61.png)

**Comment by maechler** [comment]
I am glad the issue is solved! In my understanding however the order of the pages should not matter. What should matter is, that all the pages have the static TypoScript template included.
