### ISSUE TITLE
Custom fonts with same family but different styles always uses "regular" style

### ISSUE THREAD

**Issue by Teddytrombone** [bithost-gmbh/pdfviewhelpers#161]
**Describe the bug**
If you use custom fonts with same family but different styles like regular and bold, then the pdf only has the regular style.

**Environment**
TYPO3 version(s): v9.5.16
pdfviewhelpers version: v2.2.2, v2.3.2

**Steps to reproduce**
Register two fonts, e.g. "font" and "fontb". "fontb" is the bold version of "font". Now create a PDF which renders an HTML string with regular and bold text using "font". In the resulting PDF, the text uses only "font".

**Comment by maechler** [comment]
@Teddytrombone Thank you very much for your bug report and providing a fix! I will have a look at it this week and release a new version.

**Comment by maechler** [comment]
I just released a new version `v2.3.3` including your fix. Thanks again very much for that!
