### ISSUE TITLE
Typoscript template for news extension doesnt work

### ISSUE THREAD

**Issue by fgerards** [bithost-gmbh/pdfviewhelpers#166]
**Describe the bug**
TypoScript static template for news-extension wont work. as the Typoscript condition is around the whole page configuration, the page type doesnt exist and you get an undefined pageType error. please fix.

**Environment**
TYPO3 version(s): 10.4 LTS
pdfviewhelpers version: latest

**Steps to reproduce**
Tell us how to reproduce this issue. Preferably with a fresh TYPO3 installation and no additional extensions installed apart from `EXT:pdfviewhelpers`.

**Expected behavior**

**Possible solution**
Do you already have an idea how to solve this issue?

**Comment by maechler** [comment]
@fgerards Thanks for reporting! I just verified this bug and will fix it probably this week.

**Comment by maechler** [comment]
@fgerards Should be fixed with https://github.com/bithost-gmbh/pdfviewhelpers/pull/168/commits/424bf33e17a25926b771a1dccb7a225037cfcc08.

**Comment by maechler** [comment]
I just released `v2.3.4` which fixes this issue. If you like the extension, please consider giving it a star on GitHub :)
