### ISSUE TITLE
No more compatibility with PHP 5.4

### ISSUE THREAD

**Issue by Oktopuce** [bithost-gmbh/pdfviewhelpers#17]
Hi,

The last version of the extension is no more compatible with PHP 5.4 because of this line :

$this->configurationManager = GeneralUtility::makeInstance(ConfigurationManager::class);

in 5.4 you can use this : 

$this->configurationManager = GeneralUtility::makeInstance(\get_class(new \TYPO3\CMS\Extbase\Configuration\ConfigurationManager));

Reagrds,
Florian

**Comment by maechler** [comment]
Hi @Oktopuce 

Thanks for reporting that issue! We will fix it soon and release a new version!

**Comment by Oktopuce** [comment]
Hi,

There is another compatibility problem the extension cannot be installed on Typo3 6.2.0 because there is a problem with the composer : 

Oops, an error occurred!
The package "pdfviewhelpers" depends on "typo3/cms" which is not present in the system.

Florian

**Comment by Oktopuce** [comment]
I found this solution for composer : change the package name from typo3/cms to typo3/cms-cms.

**Comment by maechler** [comment]
@Oktopuce That seems a little strange to me, especially since there is no composer package `typo3/cms-cms`. The official TYPO3 composer package name is `typo3/cms` found [here](https://packagist.org/packages/typo3/cms).

When exactly does that error occur?

**Comment by Oktopuce** [comment]
This occurred when I tried to install the version 1.2.0 on a typo3 6.2.0.
I found that solution on the web and didn't look further but may be it's "typo3/cms-core" instead of "typo3/cms-cms". 

Look here : https://review.typo3.org/#/c/35501/2/composer.json

**Comment by maechler** [comment]
As far as I can see is `typo3/cms-core` now part of the package `typo3/cms`. See https://github.com/TYPO3/TYPO3.CMS/blob/master/composer.json#L92
There is also no package `typo3/cms-core` on packagist.org.

I also tested installing the extension on TYPO3 6.2.16 using the extension manager, that worked for me. 

Do you install it with the extension manager or via composer? What commands do you use? Have you tested it with a fresh installation of TYPO3 6.2? What could I do to reproduce the issue?

**Comment by Oktopuce** [comment]
I installed it via the Extension Manager. I didn't test it on a fresh installation.

**Comment by maechler** [comment]
Hmm..I could not reproduce that issue. Although I can not yet fully grasp the problem or the way TYPO3 handles the composer.json files, I think the dependency should be `typo3/cms-core` as you suggested.
See also https://wiki.typo3.org/Composer.

**Comment by maechler** [comment]
I fixed these issues and created a new release. Soon the extension will be available in TER.
I will close here, thanks for reporting the issues!
