### ISSUE TITLE
Lots of error messages in TYPO3 log regarding globalVar = TSFE:type = 28032013

### ISSUE THREAD

**Issue by cdaecke** [bithost-gmbh/pdfviewhelpers#175]
**Describe the bug**
The extension produces lots of errors in the TYPO3 logfile when including the static template `pdfviewhelpers - EXT:news`:

>Wed, 23 Sep 2020 15:14:03 +0200 [ERROR] request="918efe0c5c9a5" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed. - {"expression":"globalVar = TSFE:type = 28032013"}

As the error message states, this is due to the fact, that TYPO3 10 does not support the old typoscript conditions anymore.

**Environment**
TYPO3 version:`v10.4.8`
pdfviewhelpers version: `v2.3.4`

**Steps to reproduce**
Just install the extension and include the static template `pdfviewhelpers - EXT:news`.

**Expected behavior**
No entries in logfile.

**Possible solution**
Remove TYPO3 8 compatibility so you can remove the condition in `TypoScriot/Extensions/News/Setup.txt`

**Last but not least: Great extension, thank you for sharing!**

**Comment by cdaecke** [comment]
Just found this https://github.com/bithost-gmbh/pdfviewhelpers/issues/169, so you are already aware of this issue ;-)

**Comment by maechler** [comment]
@cdaecke Thanks for your well written error report! I wanted to add support for TYPO3 v10 in a backwards compatible manner. But I agree that we could probably drop support for TYPO3 v8 now in favour of a clean error log. 

As a workaround you could simply include the part of `TypoScript/Extensions/News/setup.txt` where it says `Type condition for TYPO3 9 and 10 LTS` in your own TypoScript setup and remove the static template.

If you like the extension, please consider giving it a star on GitHub :)

**Comment by maechler** [comment]
We should also update the TypoScript conditions in the documentation to `[getTSFE().type == 28032013]`.

**Comment by maechler** [comment]
This should be fixed with `v2.4.0` as we dropped support for TYPO3 v8. I will however keep this issue open to update the documentation.
