### ISSUE TITLE
No class named Bithost\Pdfviewhelpers\Hooks\TypoScriptFrontendController

### ISSUE THREAD

**Issue by kurtwithslc** [bithost-gmbh/pdfviewhelpers#177]
**Describe the bug**
After installing pdfviewhelpers installation is broken in Frontend, and later on also in backend.
I get this error:
No class named Bithost\Pdfviewhelpers\Hooks\TypoScriptFrontendController
in /html/typo3/typo3_src-10.4.9/typo3/sysext/core/Classes/Utility/GeneralUtility.php line 3332
at TYPO3\CMS\Core\Utility\GeneralUtility::callUserFunction('Bithost\\Pdfviewhelpers\\Hooks\\TypoScriptFrontendController->isOutputting', array('pObj' => object(TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController), 'enableOutput' => true), object(TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController))

if Error comes up in Backend, its necessary to remove extension and to clean up autoloader files from any line with .../pdfviewhelpers/...
Otherwise, typo3 installation is not reachable anymore

**Environment**
TYPO3 version(s): [`10.4.9`]
pdfviewhelpers version: [e.g. `2.3.4`]
static template is included in Root Template
multi domain configuration

**Steps to reproduce**
Install pdfviewhelpers, include static template, clear all caches, call frontend

**Expected behavior**
sites and pages with and without use of pdfviewhelpers are callable without error

**Possible solution**
none

**Comment by maechler** [comment]
@kurtwithslc I am afraid I cannot reproduce the issue with the versions `10.4.9` of TYPO3 and `pdfviewhelpers` `2.3.4`. Both installing the extension using TER and composer works as expected. The TYPO3 core automatically updates the autoload information and I do not get any error.

Is it possible that you either installed the extension by just copying the source files to `typo3conf/ext` without dumping the autoload information in the Install Tool? Or that the folder `typo3conf/autoload` was not writable?

Are there any errors during the installation of `EXT:pdfviewhelpers` (especially regarding the autoload information)?

**Comment by maechler** [comment]
Great! Although I do not think that the issue was related to the PHP version used. If you like the extension, please consider giving it a star on GitHub!
