### ISSUE TITLE
example for pdf form to fill in fields

### ISSUE THREAD

**Issue by averlon** [bithost-gmbh/pdfviewhelpers#183]
Hi,
I am looking for an example to fill in form fields of an existing pdf-file and store the result in a different file.

The values to fill in shall be taken from the user record of some folder.

Is that possible with the extension and is there an example for such way to use it?

Regards
Karl-Heinz

**Comment by maechler** [comment]
Hi @averlon 

I do not think it would be easily possible to fill in form fields of an existing PDF. We currently use [FPDI](https://www.setasign.com/products/fpdi/about/) to load existing PDFs as a template and [PdfParser](https://github.com/smalot/pdfparser) to load the contents of a PDF in the unit tests. Both of them do not seem to offer the possibility to alter form fields.

You could however try to rebuild the form using the `pdf:html` ViewHelper and an HTML form: https://tcpdf.org/examples/example_054/

Another way could be to implement [a custom ViewHelper](https://docs.typo3.org/p/bithost-gmbh/pdfviewhelpers/master/en-us/ConfigurationReference/AdvancedCustomization/Index.html) and use the TCPDF form methods directly: https://tcpdf.org/examples/example_014/

However I have not exhaustively searched for possibilities, if you find any PHP based solution, preferably working with TCPDF, I think you could integrate it.

**Comment by maechler** [comment]
@averlon Did you find a solution for your problem?

**Comment by maechler** [comment]
Closing because of no response.
