### ISSUE TITLE
Newer TYPO3 versions will require extension key in composer.json

### ISSUE THREAD

**Issue by tpinne** [bithost-gmbh/pdfviewhelpers#184]
Message during `composer install/update`:

> The TYPO3 extension package "bithost-gmbh/pdfviewhelpers", does not define an extension key in its composer.json. Please report this to the author of this package. Specifying the extension key will be mandatory in future versions of TYPO3 (see: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra)

The missing piece:

 ```
  "extra": {
    "typo3/cms": {
      "extension-key": "pdfviewhelpers"
    }
  }
```

**Comment by maechler** [comment]
@tpinne Thanks for reporting! This has already been fixed: https://github.com/bithost-gmbh/pdfviewhelpers/pull/182
I have however not created a release since, as it only triggers a warning.

**Comment by tpinne** [comment]
Ah ok. I’ve only looked at the master and didn’t saw it there. 
But because the warning encourages people to inform the developer there might be more people reporting this :)

**Comment by maechler** [comment]
@tpinne I created a new release yesterday that adds the extension key to the composer.json :)
