### ISSUE TITLE
TYPO3 11.5 support

### ISSUE THREAD

**Issue by aimeos** [bithost-gmbh/pdfviewhelpers#189]
TYPO3 11.5 has been released last week. When will be a compatible version available?

**Comment by maechler** [comment]
@aimeos I just tested the example PDFs that are shipped with the extension with TYPO3 `v11.5`, the rendering seems to work perfectly without any changes necessary. However there seems to be a caching issue when a page is called multiple times, but I guess we can just use the `internal` option in `$GLOBALS['TSFE']->set_no_cache` or users could set `disableNoCacheParameter` to `false`.
I will still have to test the `EXT:news` integration and any testing and feedback from your side would also be very welcome! We have no timetable yet for `v11.5` compatibility, but it looks like being just around the corner.

**Comment by maechler** [comment]
A new release `v2.4.0` with TYPO3 v11 support is available now.
