### ISSUE TITLE
ConfigurationManager not initialized correctly 

### ISSUE THREAD

**Issue by maechler** [bithost-gmbh/pdfviewhelpers#19]
The configurationManager should be retrieved from the Extbase Object Manager in order to be correctly initialized.

Replace the following line:
https://github.com/bithost-gmbh/pdfviewhelpers/blob/0a02f835e63e244f65d6f4405056878070e7789e/Classes/ViewHelpers/AbstractPDFViewHelper.php#L57

with: 
```PHP
$objectManager = GeneralUtility::makeInstance('TYPO3\\CMS\\Extbase\\Object\\ObjectManager');
$this->configurationManager = $objectManager->get('TYPO3\\CMS\\Extbase\\Configuration\\ConfigurationManager');
```

A possible error resulting from that issue could be:

`Fatal error: Call to a member function getConfiguration() on null in /usr/share/typo3/typo3_src-7.6.16/typo3/sysext/extbase/Classes/Configuration/ConfigurationManager.php on line 128`

**Comment by macjohnny** [comment]
+1

**Comment by maechler** [comment]
I fixed this and will include it in the next release coming soon.
