### ISSUE TITLE
Tables unexpected gap

### ISSUE THREAD

**Issue by luhell** [bithost-gmbh/pdfviewhelpers#202]
**Describe the bug**
While creating a standalone PDF via a template i try to use tables inside of an pdf:html viewhelper, but as soon as iam using tds there is a gap between them that is not removable by inline css

**Environment**
TYPO3 version(s): 10.4.26
pdfviewhelpers version:  2.4.0

**Comment by maechler** [comment]
Closing because of no response within almost 6 months.
