### ISSUE TITLE
PHP 8 error in ColumnViewHelper if width isn't set

### ISSUE THREAD

**Issue by rk-mxp** [bithost-gmbh/pdfviewhelpers#223]
**Describe the bug**
When using the ColumnViewHelper without width the following PHP error occurs with PHP 8:

```
PHP Runtime Deprecation Notice: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /.../typo3conf/ext/pdfviewhelpers/Classes/ViewHelpers/ColumnViewHelper.php line 65
```

**Environment**
TYPO3 version(s): 11.5
PHP Version: 8.2
pdfviewhelpers version: 2.5.0

**Steps to reproduce**
Add a ColumnViewHelper to the PDF like this:
```
<pdf:multiColumn>
<pdf:column>
    <pdf:list listElements="{
    0: 'Option 1',
    1: 'Option 2',
    2: 'Option 3'
}" />
</pdf:column>
<pdf:column>
    <pdf:list listElements="{
    0: 'Option 4',
    1: 'Option 5',
    2: 'Option 6'
}" />
</pdf:column>
</pdf:multiColumn>
```

**Expected behavior**
The columns are rendered

**Possible solution**
The problem is the `if` in the `initialize` function of the `ColumnViewHelper`:

```php
if (strlen($this->arguments['width'])) {
    if ($this->validationService->validateWidth($this->arguments['width'])) {
        $multiColumnContext['columnWidth'] = $this->conversionService->convertSpeakingWidthToTcpdfWidth($this->arguments['width'], $multiColumnContext['pageWidthWithoutMargins']);
    }
} else {
    $multiColumnContext['columnWidth'] = $multiColumnContext['defaultColumnWidth'];
}
```

Replacing `strlen` with `!empty` as test function should fix the problem

**Comment by maechler** [comment]
@Barakur Thank you very much for the detailed error report! I'll have a look at it.

**Comment by maechler** [comment]
This should already be solved in the current main branch by casting the width to a string:
