### ISSUE TITLE
ViewHelper to attach another PDF

### ISSUE THREAD

**Issue by georgringer** [bithost-gmbh/pdfviewhelpers#227]
1st of all thanks to the extension! 

We are using it in one project to create invoices. The requirement was to attach the receipts which worked nicely in the start by just using `<pdf:image>` but attaching PDF receipts was not possible when the pdfs contained more than one page. Additionally the quality was bad due to compressions

The solution was to combine the PDF generated by us and the receipts. There are couple of code snippets online which have been helpful to turn that into a running and working VH

**Comment by maechler** [comment]
@georgringer Thank you very much for that contribution! This has actually been requested already a long time ago in #139. I will merge your PR and if I find the time, rework the API a bit towards what is described in #139 before it is released.
