### ISSUE TITLE
TYPO3 12, non-composer: Fpdi not found

### ISSUE THREAD

**Issue by robinson2** [bithost-gmbh/pdfviewhelpers#229]
**Environment**
TYPO3 version(s): 12.4.4 non-composer
pdfviewhelpers version: github master 2023/08/07

I tried the example https://docs.typo3.org/p/bithost-gmbh/pdfviewhelpers/main/en-us/Examples/BasicUsage/Index.html and got the error "file /html/typo3/typo3conf/ext/pdfviewhelpers/Classes/Model/BasePDF.php, line 41: Class "setasign\Fpdi\Tcpdf\Fpdi" not found". 

The TypoScript Template is inculded.

**Comment by maechler** [comment]
@robinson2 As part of the next major release we removed the TCPDF and FPDI source files from the repository. I want however to make sure the TER releases still include them, just haven't fully tested it yet:

https://github.com/bithost-gmbh/pdfviewhelpers/blob/f17980f15a8b2cfc45215b234ea2d2bc1cfac8c2/composer.json#L61-L79

If you would like to use the unreleased version already, you can manually download the sources and place them in `Resources/Private/PHP/tcpdf` and `Resources/Private/PHP/fpdi` respectively. The download links you find in the code snippet above. I think the implementation in the main branch should be pretty stable already.
