### ISSUE TITLE
Support TYPO3 v12.4 LTS

### ISSUE THREAD

**Issue by DanielSiepmann** [bithost-gmbh/pdfviewhelpers#233]
**Is your feature request related to a problem? Please describe.**
We want to update an installation to 12.4 LTS where we make use of this extension.

**Describe the solution you'd like**
Best would be to have a v12.4 LTS compatible version to be released.

**Describe alternatives you've considered**
We currently give the main branch a try.

**Additional context**
Are there any plans or timings regarding v12.4 LTS support from your end?
Please don't feel pushed by this issue. We just want to ask prior investing unnecessary time ourselves.

**Comment by maechler** [comment]
@DanielSiepmann The current `main` branch is already compatible with `v12.4` and quite stable. All our tests and examples are working, I think it's okay if you start using what is in the `main` branch.
There are some PHP warning fixes and maintenance tasks missing before we can create a public release. I hope I'll find time to do this in the next 1-2 months.

**Comment by maechler** [comment]
I just created an official `v3.0.0` release supporting `v12.4`, please let me know if you encounter any issues.
