### ISSUE TITLE
Warning in TCPDF on PHP 7.1.x

### ISSUE THREAD

**Issue by koritnik** [bithost-gmbh/pdfviewhelpers#28]
Trying to render content with more than one link in it, runs in a "Illegal string offset 'url'" warning in tcpdf.php, which breaks the PDF rendering. Updating to tecnickcom/TCPDF 6.2.13 solves this problem.

**Comment by macjohnny** [comment]
resolved in #29 
thanks @koritnik for your issue report and your contribution!
