### ISSUE TITLE
Add viewhelper for header / footer elements

### ISSUE THREAD

**Issue by macjohnny** [bithost-gmbh/pdfviewhelpers#31]

**Comment by macjohnny** [comment]
Currently, it is necessary to extend the class defined in `plugin.tx_pdfviewhelpers.settings.config.class`, overwrite the `Header()` or `Footer()` method or both and set the custom class in `plugin.tx_pdfviewhelpers.settings.config.class`

The `Header()` and `Footer()` methods are called for every new page added.

**Comment by macjohnny** [comment]
See the example in https://github.com/bithost-gmbh/pdfviewhelpers/blob/master/Classes/Model/BithostTCPDF.php#L42

**Comment by PeterSchuhmann** [comment]
I think this solution only works if you have a static header and footer. but what if you want to add dynamic data like data from your model?

**Comment by maechler** [comment]
I think @macjohnny is proposing a feature similar to this:

```html
<pdf:document>
   <pdf:header>
       <pdf:text>Some headline text: {yourVariable}</pdf:text>
   </pdf:header>
   <pdf:footer>
       <pdf:text>Footer, we are on page {currentPage}</pdf:text>
   </pdf:footer>
   <pdf:page>
       <pdf:header>Maybe we can overwrite header and footer on pages?</pdf:header>
   </pdf:page>
</pdf:document>
```

It should be possible to define header and footer on document level. Probably there should also be the possibility to overwrite header and footer on page level and variables like `{currentPage}` should be provided. In this scenario you could use dynamic data from your model. 
I am not sure however how this feature could be implemented. Maybe it is possible to store a reference to e.g. `HeaderViewHelper` and then render its children on each page with a new set of variables like `{currentPage}`.

**Comment by maechler** [comment]
I started progress on this one and created a working example: https://github.com/bithost-gmbh/pdfviewhelpers/commit/bb942c39dbae862d1ca2d6c4aca36ed952cae919
https://github.com/bithost-gmbh/pdfviewhelpers/tree/feature/headerFooterSupport

It seems to be easier than expected, although it still needs some effort until it is ready to be used.

**Comment by maechler** [comment]
This is implemented and tested in the current `develop` branch and will be released as part of `pdfviewhelpers` `v2`.

**Comment by maechler** [comment]
@Gernott I just released `pdfviewhelpers` `v2`, it contains header and footer ViewHelpers and lots of other features. If you still feel like sponsoring, a contribution would be very welcome!
See https://github.com/bithost-gmbh/pdfviewhelpers#support-development
