### ISSUE TITLE
Bug: Crash when using in TYPO3 Backend (Regression)

### ISSUE THREAD

**Issue by macjohnny** [bithost-gmbh/pdfviewhelpers#35]
As pointed out by @liayn in https://github.com/bithost-gmbh/pdfviewhelpers/commit/42385a4842ad0eb0574789877bb91400de261bce#r27355212 checking for `TSFE` crashes in backend

**Comment by macjohnny** [comment]
@maechler could you have a look at it?

**Comment by maechler** [comment]
I will have a look at this tomorrow and create a new release if everything is fine. Thanks @liayn and @macjohnny!
