### ISSUE TITLE
posX and posY not working

### ISSUE THREAD

**Issue by PeterSchuhmann** [bithost-gmbh/pdfviewhelpers#37]
Hi,

great extension. thank you fort that. 

I am having a little issue that the posX and posY attribute is being ignored for every element. I think I already found the issue. posX and posY gets set every time even the attribute for it exists:

```
diff --git a/Classes/ViewHelpers/AbstractContentElementViewHelper.php b/Classes/ViewHelpers/AbstractContentElementViewHelper.php
index 7ee5572..5fb3fbc 100644
--- a/Classes/ViewHelpers/AbstractContentElementViewHelper.php
+++ b/Classes/ViewHelpers/AbstractContentElementViewHelper.php
@@ -59,8 +59,13 @@ abstract class AbstractContentElementViewHelper extends AbstractPDFViewHelper {
                        $this->isValidHeight($this->arguments['height']);
                }
 
-               $this->arguments['posX'] = $this->getPDF()->GetX();
-               $this->arguments['posY'] = $this->getPDF()->GetY();
+               if (is_null($this->arguments['posX'])) {
+                       $this->arguments['posX'] = $this->getPDF()->GetX();
+               }
+
+               if (is_null($this->arguments['posY'])) {
+                       $this->arguments['posY'] = $this->getPDF()->GetY();
+               }
        }
 
        /**
```

This way a user can put information in the footer without creating a new template file. Is it possible for you to add this fix to your repo? thank you in advance.

best regards
Peter

**Comment by maechler** [comment]
Hi Peter,
That code looks strange indeed. I will try to have a look at it soon. Thanks for reporting that issue!
Maybe you can fix that issue in your code using an XCLASS until this is included in an official release.
