### ISSUE TITLE
List package on packagist.org 

### ISSUE THREAD

**Issue by benjaminhirsch** [bithost-gmbh/pdfviewhelpers#53]
Could you please list the package on packagist.org? This would make the handling alot easier and I don't have to use the "old" TYPO3-Repostiory (https://composer.typo3.org/) in my composer.json as an additional repostiory. ;)

**Comment by maechler** [comment]
Sure! I just added the package: https://packagist.org/packages/bithost-gmbh/pdfviewhelpers
