### ISSUE TITLE
PHP 7.2

### ISSUE THREAD

**Issue by r3h6** [bithost-gmbh/pdfviewhelpers#56]
Compatibility with PHP 7.2

**Comment by macjohnny** [comment]
@r3h6 thanks for opening this issue. could you please add some information about problems that currently occur with PHP 7.2?

**Comment by maechler** [comment]
Probably nothing except the version constraint in `ext_emconf.php`?

**Comment by r3h6** [comment]
So far none, just version constraint in composer

**Comment by maechler** [comment]
@r3h6 Actually there is no version constraint in the file composer.json:
https://github.com/bithost-gmbh/pdfviewhelpers/blob/e81149be696c52df3ae79de2226976636b414f08/composer.json#L19-L21

See also _requires_ on https://packagist.org/packages/bithost-gmbh/pdfviewhelpers#1.5.1

Is it possible that you use the TYPO3 composer repository (https://composer.typo3.org/) and that TYPO3 adds the PHP constraint based on `ext_emconf.php`?

We will definitely raise the requirement, but maybe you could solve the issue by getting the extension from Packagist.

**Comment by r3h6** [comment]
Version from packagist works fine, thanks

**Comment by maechler** [comment]
I reopened this issue, because we will raise the version constraint in `ext_emconf.php` and probably also add the to `composer.json`.
