### ISSUE TITLE
Fontsize wrong in pdf:html

### ISSUE THREAD

**Issue by Gernott** [bithost-gmbh/pdfviewhelpers#57]
Since version 1.5.2 the fontsize of text inside of <pdf:html> is too small.
Example code of my extension:
```
<pdf:html>
<table style="font-size:9px;><tr><td>Text</td></tr></table>
</pdf:html>
```
I need to change the fontsize from 9 to more than 20, to get the same size as with version 1.5.1 and older.

Perhaps this is an TCPDF issue?

**Comment by macjohnny** [comment]
I had a quick look at the https://github.com/bithost-gmbh/pdfviewhelpers/compare/v1.5.1...v1.5.2 but there was no update of TCPDF. 
Also, the HtmlViewHelper did not change, see https://github.com/bithost-gmbh/pdfviewhelpers/compare/v1.5.1...v1.5.2#diff-fa07fbdb277690316bd247f007ae133fR39

@Gernott can you spot a functional difference in the HtmlViewHelper?
Are you sure it works correctly with `1.5.1`?
Are you sure your stylesheet is applied correctly?

**Comment by maechler** [comment]
I could not reproduce that issue, I tested your code with `1.5.1` and `1.5.2` and got exactly the same results.

@Gernott Have you found out something in the meantime? Is there any additional configuration, that could cause that error?

**Comment by maechler** [comment]
@Gernott Any update on this?

**Comment by Gernott** [comment]
I cannot reproduce the issue on my home PC and on my office PC.
I want to try it on my laptop in the next days. There appears the problem.

**Comment by maechler** [comment]
@Gernott Have you been able to reproduce this issue? 
Otherwise I will close this issue and you could reopen it or create a new one if the error occurs again.

**Comment by Gernott** [comment]
If possible, please give me 2 weeks more time. I'm on holiday until 2nd of september.

**Comment by maechler** [comment]
Sure, no worries. Enjoy your holidays!

**Comment by Gernott** [comment]
I'm sorry, I cannot reproduce it anymore. I tried a lot of things, but it works perfect. If I find this case again, I write a new ticket with more details.
