### ISSUE TITLE
[FEATURE] Add fpdi

### ISSUE THREAD

**Issue by ste101** [bithost-gmbh/pdfviewhelpers#7]
Please add the fpdi library and add an example how to use it:
https://www.setasign.com/products/fpdi/downloads/

**Comment by maechler** [comment]
That is a great idea! We will definitely add support for FPDI.

In the mean time you could already use certain features by providing your own PDF class:

`plugin.tx_pdfviewhelpers.settings.config.class = Vendor\Extension\Model\FPDI`

https://docs.typo3.org/typo3cms/extensions/pdfviewhelpers/Example/Index.html

**Comment by maechler** [comment]
I have added basic support for FPDI. You can now load a PDF on the DocumentViewHelper with the attribute sourceFile and use it with the PageViewHelper attribute importPage.

https://docs.typo3.org/typo3cms/extensions/pdfviewhelpers/TemplatePDF/Index.html
