### ISSUE TITLE
No content in outputPath!

### ISSUE THREAD

**Issue by AureliusHogan** [bithost-gmbh/pdfviewhelpers#97]
I upgraded from version 1.x to version 2.0 and did all of the upgrading changes.
```html
<pdf:document sourceFile="fileadmin/template.pdf" outputPath="typo3temp/registration.pdf">
```
This statement leads to a registration.pdf equal template.pdf. If I use **outputDestination="inline"** the result has the content of template.pdf **inlcuding** all pdf:text statements I've set. 

Why does registration.pdf don't carry any content? What could be missing?

**Comment by maechler** [comment]
If you use `outputDestination="inline"` then it is only returned inline to the browser, but not saved to the filesystem. If you want to save it to the filesystem you should use `outputDestination="file"` or outputDestination="file-inline" to save it AND return it to the browser. 
Please see: https://docs.typo3.org/typo3cms/extensions/pdfviewhelpers/ConfigurationReference/TypoScriptReference/Index.html#document-outputdestination

Does this solve your issue?

**Comment by AureliusHogan** [comment]
No that doesn't change anything. Thx. for the fast reply.

It's not that the file is not generated. The problem is that the content inside of the document is not generated. If I use "file-inline" the document shown is correct but the document saved is without content.

**Comment by maechler** [comment]
@AureliusHogan Currently I can not reproduce that issue. It seems strange to me, that the document that is returned inline, has different content than the file that is saved, because `TCPDF` actually reads the saved file to return it's content. See:

https://github.com/bithost-gmbh/pdfviewhelpers/blob/16473677eee6ff261c6ebe80bc57c7ffd0181ef9/Resources/Private/PHP/tcpdf/tcpdf.php#L7674-L7679

and

https://github.com/bithost-gmbh/pdfviewhelpers/blob/16473677eee6ff261c6ebe80bc57c7ffd0181ef9/Resources/Private/PHP/tcpdf/tcpdf.php#L7689

Does this also happen with the example `Extend Existing PDFs`?
Did this work with `v1.x`? 
Are there any errors in the error log?
Can you try to open the document that is saved to the filesystem with your browser?
Can you try to debug that place in TCPDF?
Can you provide your template?

**Comment by AureliusHogan** [comment]
Yes, I just now noticed, that Adobe Acrobat says the document has an error. So I tried to validate it as you mention in your documentation. The result is: 
![image](https://user-images.githubusercontent.com/30202934/47105257-b5d3d280-d243-11e8-9f1d-2ac1e9634498.png)

Now the question is, how to find the problem? The code I use is rather simple:
```html
<pdf:document sourceFile="typo3conf/ext/pdfviewhelpers/Resources/Public/Examples/ExtendExistingPDFs/pdf_template.pdf" title="ESM PDF-Test" outputDestination="file-inline" outputPath="typo3temp/test.pdf">
	<pdf:page autoPageBreak="1" importPage="1" margin="{top: 58, right: 20, bottom: 40, left: 20}">
		<pdf:text>
			wir freuen uns, dass Sie sich für den folgenden Kurs angemeldet haben:
		</pdf:text>
		<pdf:text> </pdf:text>
		<pdf:headline><f:format.case mode="upper">Innerer Garten</f:format.case></pdf:headline>
		<pdf:text><f:format.raw>Hier kannst Du pflanzen was immer Du moechtest. Wichtig ist lediglich der Bezug zur Natur. Nutze die Demeter Gedanken.</f:format.raw></pdf:text>
		<pdf:text> </pdf:text>
	</pdf:page>
</pdf:document>
```

**Comment by maechler** [comment]
There seems to be an issue with the `renderHeader` and `renderFooter` methods in `BasePDF`. You could try to provide your own class and overwrite these methods:

```php
<?php
namespace Vendor\YourExtension\Model;

class MyPDF extends \Bithost\Pdfviewhelpers\Model\BasePDF
{
    public function renderHeader()
    {
    }

    public function renderFooter()
    {
    }
}
```

```TypoScript
plugin.tx_pdfviewhelpers.settings {
    config {
       class = Vendor\YourExtension\Model\MyPDF
    }
}
```

As long as you do not need the header and footer ViewHelpers, this should work. I will investigate that issue. Thanks again for reporting!

**Comment by maechler** [comment]
@AureliusHogan I just released a new version `v2.0.1` that should fix that issue. It would be nice if you could update the extension, remove the fix from yesterday and test whether this works for you.

If you like the project, please consider giving it a star :)

**Comment by AureliusHogan** [comment]
Yes, now everything is fine. And it seems like it is a little faster even.
Good job!
Perfekt support!

**Comment by maechler** [comment]
Perfect, thanks for reporting and testing!
